name: finals_fe
description: "A finals project app"
publish_to: 'none'

version: 0.0.1+0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  connectivity_plus: ^6.1.2
  dartz: ^0.10.1
  device_info_plus: ^11.2.1
  dio: ^5.4.2+1
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_libphonenumber: ^2.5.0
  flutter_local_notifications: ^18.0.1
  flutter_native_contact_picker: ^0.0.7
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.5
  flutter_web_auth: ^0.5.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.0
  google_maps_flutter: ^2.10.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.2
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  network_info_plus: ^6.1.3
  package_info_plus: ^8.1.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  dependency_validator: ^4.1.2
  flutter_gen_runner: 5.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"

flutter_gen:
  output: lib/utils/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/navbar/
    - assets/images/
    - .env
